spring:
  application:
    name: config-client

server:
  port: 8080

#com:
#  slowstarter:
#    exapme:
#      config:
#        client: default1

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ["health", "env"]
  #        include: ["*"]
  endpoint:
    health:
      show-details: always
